# Generated by Django 4.2.6 on 2023-10-12 02:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ImageField(upload_to=accounts.models.articles_image_path),
        ),
    ]
