# Generated by Django 4.2.6 on 2023-10-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
